language: elixir
elixir:
  - 1.3.2
  - 1.2.6
  - 1.1.1
otp_release:
  - 19.0
  - 18.3
  - 18.2
script:
  - if [[ "$TRAVIS_ELIXIR_VERSION" = "1.1.1" ]]; then mix test --trace; else mix coveralls.travis --trace; fi
env:
  - MIX_ENV=test
branches:
  only:
    - master
