language: elixir
elixir:
  - 1.3.4
  - 1.2.6
otp_release:
  - 19.1
  - 19.0
  - 18.3
  - 18.2
script:
  - mix coveralls.travis --trace
env:
  - MIX_ENV=test
branches:
  only:
    - master
